name: Build QR Code App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [linux/amd64, windows/amd64, darwin/amd64]
    runs-on: ${{ matrix.platform == 'darwin/amd64' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
    - name: Install Linux Dependencies
      if: matrix.platform == 'linux/amd64'
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev
    - name: Install Windows Cross-Compile Tools
      if: matrix.platform == 'windows/amd64'
      run: sudo apt-get update && sudo apt-get install -y mingw-w64
    - name: Install Frontend Dependencies
      run: cd frontend && npm install
    - name: Build
      run: wails build -platform ${{ matrix.platform }}
    - name: Package Linux
      if: matrix.platform == 'linux/amd64'
      run: |
        mkdir qr-code-app-linux-amd64
        cp build/bin/qr-code-app qr-code-app-linux-amd64/
        tar -czvf qr-code-app-linux-amd64.tar.gz qr-code-app-linux-amd64
    - name: Package Windows
      if: matrix.platform == 'windows/amd64'
      run: |
        mkdir qr-code-app-windows-amd64
        cp build/bin/qr-code-app.exe qr-code-app-windows-amd64/
        zip -r qr-code-app-windows-amd64.zip qr-code-app-windows-amd64
    - name: Package macOS
      if: matrix.platform == 'darwin/amd64'
      run: |
        mkdir qr-code-app-darwin-amd64
        cp build/bin/qr-code-app qr-code-app-darwin-amd64/
        zip -r qr-code-app-darwin-amd64.zip qr-code-app-darwin-amd64
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qr-code-app-${{ matrix.platform }}
        path: qr-code-app-${{ matrix.platform == 'linux/amd64' && 'linux-amd64.tar.gz' || matrix.platform == 'windows/amd64' && 'windows-amd64.zip' || 'darwin-amd64.zip' }}
