name: Build QR Code Generator

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - platform: 'linux/amd64'
            os: 'ubuntu-22.04'  # Changed from ubuntu-latest to 22.04
          - platform: 'windows/amd64'
            os: 'windows-latest'
          - platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.config.os }}
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # Step 3: Install Linux dependencies
      - name: Install Linux dependencies
        if: matrix.config.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtk-3-dev libwebkit2gtk-4.0-dev

      # Step 4: Install Windows dependencies
      - name: Install Windows dependencies
        if: matrix.config.os == 'windows-latest'
        run: choco install -y mingw

      # Step 5: Install macOS dependencies
      - name: Install macOS dependencies
        if: matrix.config.os == 'macos-latest'
        run: xcode-select --install || true

      # Step 6: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Step 7: Install Wails CLI
      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.8.0

      # Step 8: Install npm dependencies
      - name: Install npm dependencies
        run: |
          cd frontend
          npm ci
          npm run build

      # Step 9: Build Wails app
      - name: Build Wails app
        run: |
          wails build -platform ${{ matrix.config.platform }} -o QRCodeGenerator
        env:
          GO111MODULE: on

      # Step 10: Debug build output
      - name: List build output
        run: |
          ls -la build/bin || dir build\bin
        shell: bash {0}

      # Step 11: Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QRCodeGenerator-${{ matrix.config.platform == 'linux/amd64' && 'linux-amd64' || matrix.config.platform == 'windows/amd64' && 'windows-amd64' || 'darwin-universal' }}
          path: build/bin/*
          if-no-files-found: error
