name: Build QR Code App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - platform: 'windows/amd64'
            os: 'windows-latest'
          - platform: 'darwin/amd64'
            os: 'macos-latest'
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Linux Dependencies
        if: matrix.config.platform == 'linux/amd64'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev build-essential
          sudo ln -s /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc || echo "Symlink already exists"

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci || npm install
          npm run build --verbose

      - name: Build Wails App
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: 'qr-code-app'
          build-platform: ${{ matrix.config.platform }}
          package: true
          go-version: '1.21'
          wails-version: 'v2.9.0'  # Per README note for stability
          args: '--verbose'

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qr-code-app-${{ matrix.config.platform }}
          path: |
            build/bin/*
            *.log
