name: Build QR Code Generator

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0, v2.3.1, etc.

env:
  NODE_OPTIONS: "--max-old-space-size=4096" # Prevents out-of-memory issues

jobs:
  build:
    strategy:
      fail-fast: false # Continue building other platforms even if one fails
      matrix:
        name: ['QRCodeGenerator'] # Single app name for all platforms
        platform: ['linux/amd64', 'windows/amd64', 'darwin/universal']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        # Ensure the order of platforms and os matches

    runs-on: ${{ matrix.os }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Use the latest stable Go version or match your local version

      # Step 3: Build the Wails app
      - name: Build Wails app
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}
          package: true # Package the app into a distributable format
          go-version: '1.22' # Match the Go version above

      # Step 4: Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-${{ matrix.platform }}
          path: build/bin/*
